---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.boolfixer.dev
  resources:
  - deploymentfreezers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.boolfixer.dev
  resources:
  - deploymentfreezers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.boolfixer.dev
  resources:
  - deploymentfreezers/status
  verbs:
  - get
  - patch
  - update
